/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Agents
         * @description List every governed agent, ordered by id.
         */
        get: operations["list_agents_api_v1_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agent
         * @description Fetch one agent by id, including its current `AgentContext`.
         */
        get: operations["get_agent_api_v1_agents__agent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/policy-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Policy Versions
         * @description The agent's append-only limit history, newest first.
         *
         *     Once implemented: `SELECT ... WHERE agent_id = :agent_id ORDER BY
         *     effective_from DESC`. `previous_version_id` always chains to a row
         *     that exists, except the very first version for an agent.
         */
        get: operations["list_policy_versions_api_v1_agents__agent_id__policy_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/trust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Trust
         * @description The agent's most recent `TrustEvaluation`.
         *
         *     Once implemented: calls `trust_engine.evaluate(decisions, context)` with
         *     the agent's full decision history and current `AgentContext`, persists
         *     the result with a minted `id`, and returns it — or, if evaluation is
         *     cached, the most recent persisted row.
         */
        get: operations["get_current_trust_api_v1_agents__agent_id__trust_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/trust/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Trust History
         * @description Every `TrustEvaluation` ever computed for this agent, newest first —
         *     what the dashboard's trust-over-time chart is built from.
         *
         *     Once implemented: `SELECT ... WHERE agent_id = :agent_id ORDER BY
         *     evaluated_at DESC`.
         */
        get: operations["list_trust_history_api_v1_agents__agent_id__trust_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit Log
         * @description The complete hash-chained event log, newest first. Read-only —
         *     nothing in this API ever mutates an existing row (that's the point).
         *
         *     Once implemented: `SELECT ... ORDER BY ts DESC`. Verifying the chain
         *     (recomputing each `hash` from `prev_hash` + the row's own payload) is a
         *     read-side operation a caller can do against this same data, not
         *     something the backend does on every read.
         */
        get: operations["list_audit_log_api_v1_audit_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit Samples
         * @description List sampled decisions pulled for human review, newest first.
         *
         *     Once implemented: `SELECT ... ORDER BY sampled_at DESC`, with a
         *     `?pending=true` filter for the review queue view — samples are pulled
         *     at `sampling_rate_of(agent.current_rung)` (shared/constants.py) as
         *     decisions are recorded, not on a schedule.
         */
        get: operations["list_audit_samples_api_v1_audit_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-samples/{sample_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Audit Sample
         * @description Record a human review of one sampled decision. REVIEWER or ADMIN only.
         *
         *     Once implemented: writes `reviewed_at`/`reviewer`/`verdict`/
         *     `reviewer_action` onto the `audit_samples` row, and — if `verdict` is
         *     `DISAGREED` — emits `SAMPLE_REVIEW_DISAGREEMENT`
         *     (shared/reason_codes.py) into the agent's next trust evaluation, since
         *     a disagreeing sample is itself evidence. This stub validates the sample
         *     exists and is still pending, then returns a copy reflecting the
         *     review — it does not persist it or feed the trust engine.
         */
        post: operations["review_audit_sample_api_v1_audit_samples__sample_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Decisions
         * @description List decisions, newest first.
         */
        get: operations["list_decisions_api_v1_decisions_get"];
        put?: never;
        /**
         * Create Decision
         * @description Ingest one decision from the simulator (or, eventually, a real agent).
         *
         *     Validates the agent exists and has a policy version on record, evaluates
         *     the invoice against that policy with the real Policy Engine
         *     (`app.policy.engine.evaluate_decision`), and — in one transaction —
         *     persists the invoice (if new), the decision (referencing the exact
         *     policy version in force), and a hash-chained `audit_log` entry
         *     (docs/lanes/vp.md). `within_limit` is recorded on the decision row
         *     verbatim from the Policy Engine's own output; the Policy Engine's reason
         *     code is recorded on the audit entry, never recomputed later.
         */
        post: operations["create_decision_api_v1_decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions/{decision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Decision
         * @description Fetch one decision by id.
         */
        get: operations["get_decision_api_v1_decisions__decision_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Always 200 while the process is up. No DB check yet — once
         *     persistence lands, this should also verify a connection round-trip and
         *     return 503 if the database is unreachable rather than lying about it.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recommendations
         * @description List recommendations, newest first.
         *
         *     Once implemented: `SELECT ... ORDER BY generated_at DESC`, with a
         *     `?status=PENDING` filter for the approvals queue view.
         */
        get: operations["list_recommendations_api_v1_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/{rec_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recommendation
         * @description Fetch one recommendation by id, including its full opinion panel.
         */
        get: operations["get_recommendation_api_v1_recommendations__rec_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/{rec_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Recommendation
         * @description Authorize a pending INCREASE. ADMIN only.
         *
         *     Once implemented: writes an `approvals` row (`decided_by`, `verdict`,
         *     `reason`, `decided_at`), flips `Recommendation.status` to `APPROVED`,
         *     and — in the same transaction — writes the new `policy_versions` row
         *     that actually changes `agents.current_limit`
         *     (docs/lanes/vp.md: "Never update agents.current_limit without writing a
         *     policy_versions row in the same transaction"). This stub validates the
         *     recommendation exists and is still `PENDING`, then returns a copy with
         *     `status=APPROVED` — it does not persist the change or write a policy
         *     version.
         */
        post: operations["approve_recommendation_api_v1_recommendations__rec_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/{rec_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Recommendation
         * @description Reject a pending recommendation. ADMIN only, same as approve.
         *
         *     Once implemented: writes an `approvals` row with `verdict=REJECTED` and
         *     flips `Recommendation.status` to `REJECTED`. No policy version is
         *     written — the agent's limit does not change.
         */
        post: operations["reject_recommendation_api_v1_recommendations__rec_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Simulation Run
         * @description Start a simulation run — the simulator generates `invoice_count`
         *     synthetic invoices for `phase` and posts each resulting decision to
         *     `POST /api/v1/decisions`.
         *
         *     Once implemented: enqueues the run (no Celery — see docs/CONTEXT.md's
         *     cut-scope list; a background task or a synchronous call is enough for
         *     this project's scale) and returns immediately with `status=pending`.
         *     This stub returns a freshly-minted run in `pending` status without
         *     actually starting anything.
         */
        post: operations["start_simulation_run_api_v1_simulation_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Simulation Run
         * @description Poll a run's status and, once complete, its summary accuracy/Wilson
         *     lower bound over the decisions it submitted.
         *
         *     Once implemented: `SELECT ... WHERE id = :run_id`, 404 if no row.
         */
        get: operations["get_simulation_run_api_v1_simulation_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Action
         * @description What the agent did, or what ground truth says it should have done.
         *
         *     ESCALATE is only ever an *agent* action. Ground truth is always APPROVE or REJECT,
         *     because every synthetic invoice carries a deterministic correct answer.
         * @enum {string}
         */
        Action: "APPROVE" | "REJECT" | "ESCALATE";
        /**
         * AgentContextOut
         * @description Mirrors `shared.contracts.AgentContext` field-for-field.
         */
        AgentContextOut: {
            /** Current Limit */
            current_limit: number;
            /** Decisions Since Clawback */
            decisions_since_clawback: number | null;
            /** Decisions Since Last Change */
            decisions_since_last_change: number;
            state: components["schemas"]["AgentState"];
        };
        /**
         * AgentOpinionOut
         * @description Mirrors `shared.contracts.AgentOpinion` field-for-field.
         */
        AgentOpinionOut: {
            /** Agent Name */
            agent_name: string;
            /** Concerns */
            concerns: string[];
            /** Confidence */
            confidence: number;
            /** Reasoning */
            reasoning: string;
            verdict: components["schemas"]["OpinionVerdict"];
        };
        /**
         * AgentOut
         * @description A governed agent. Backend-local resource — no `shared/` equivalent.
         *
         *     `current_rung`/`current_limit` are always kept in sync with
         *     `shared.constants.rung_of`/`limit_of` (the invariant `TrustEvaluation`
         *     documents applies here too, since this is the same pair of numbers).
         */
        AgentOut: {
            context: components["schemas"]["AgentContextOut"];
            /** Current Limit */
            current_limit: number;
            /** Current Rung */
            current_rung: number;
            /** Id */
            id: string;
            /** Name */
            name: string;
            state: components["schemas"]["AgentState"];
        };
        /**
         * AgentState
         * @enum {string}
         */
        AgentState: "probation" | "active" | "restricted" | "suspended";
        /**
         * AuditLogEntryOut
         * @description One hash-chained row. `prev_hash`/`hash` make tampering with history
         *     detectable — see docs/lanes/vp.md: "sha256(prev_hash +
         *     canonical_json(payload))". Read-only; nothing in this API ever mutates
         *     an existing row.
         */
        AuditLogEntryOut: {
            /** Actor */
            actor: string;
            /** Actor Type */
            actor_type: string;
            /** Entity Id */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            /** Event Type */
            event_type: string;
            /** Hash */
            hash: string;
            /** Id */
            id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Prev Hash */
            prev_hash: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
        /**
         * AuditSampleOut
         * @description Mirrors `shared.contracts.AuditSample` field-for-field.
         */
        AuditSampleOut: {
            /** Agent Id */
            agent_id: string;
            /** Decision Id */
            decision_id: string;
            /** Reviewed At */
            reviewed_at: string | null;
            /** Reviewer */
            reviewer: string | null;
            reviewer_action: components["schemas"]["Action"] | null;
            /** Sample Id */
            sample_id: string;
            /** Sampled At */
            sampled_at: string | null;
            verdict: components["schemas"]["ReviewVerdict"] | null;
        };
        /**
         * AuditSampleReview
         * @description Request body for `POST /api/v1/audit-samples/{sample_id}/review`.
         *
         *     Only ADMIN or REVIEWER may call this (`app/deps.py`) — reviewing sampled
         *     decisions is REVIEWER's actual job (ADR-0009); AUDITOR stays read-only.
         */
        AuditSampleReview: {
            /**
             * Reason
             * @description What the reviewer found, and why
             */
            reason: string;
            reviewer_action: components["schemas"]["Action"];
            verdict: components["schemas"]["ReviewVerdict"];
        };
        /**
         * DecisionCreate
         * @description Request body for `POST /api/v1/decisions` — the simulator's ingest path.
         *
         *     Every field needed to construct a `DecisionRecord` (see
         *     `shared.contracts.DecisionRecord`), plus `reason`
         *     (cross-cutting rule: every state-changing endpoint requires one — here,
         *     why this decision is being submitted, e.g. which simulation run or
         *     invoice-processing batch produced it).
         */
        DecisionCreate: {
            action: components["schemas"]["Action"];
            /** Agent Id */
            agent_id: string;
            /** Amount */
            amount: number;
            ground_truth: components["schemas"]["Action"];
            /** Invoice Id */
            invoice_id: string;
            /**
             * Reason
             * @description Why this decision is being submitted
             */
            reason: string;
        };
        /**
         * DecisionRecordOut
         * @description Mirrors `shared.contracts.DecisionRecord` field-for-field.
         */
        DecisionRecordOut: {
            action: components["schemas"]["Action"];
            /** Agent Id */
            agent_id: string;
            /** Amount */
            amount: number;
            /** Decided At */
            decided_at: string | null;
            /** Decision Id */
            decision_id: string;
            ground_truth: components["schemas"]["Action"];
            human_ruling: components["schemas"]["Action"] | null;
            /** Invoice Id */
            invoice_id: string;
            recommended_action: components["schemas"]["Action"] | null;
            /** Sequence */
            sequence: number;
        };
        /**
         * Direction
         * @enum {string}
         */
        Direction: "INCREASE" | "HOLD" | "CLAWBACK";
        /**
         * DriftResultOut
         * @description Mirrors `shared.contracts.DriftResult` field-for-field.
         */
        DriftResultOut: {
            /** Baseline Accuracy */
            baseline_accuracy: number | null;
            /** Baseline N */
            baseline_n: number;
            /** Critical Errors In Window */
            critical_errors_in_window: number;
            /** Detected */
            detected: boolean;
            /** Drop Pp */
            drop_pp: number | null;
            /** P Value */
            p_value: number | null;
            /** Recent Accuracy */
            recent_accuracy: number | null;
            /** Recent N */
            recent_n: number;
            severity: components["schemas"]["DriftSeverity"];
            /** Underpowered */
            underpowered: boolean;
            /** Z Statistic */
            z_statistic: number | null;
        };
        /**
         * DriftSeverity
         * @enum {string}
         */
        DriftSeverity: "NONE" | "WARNING" | "CONFIRMED" | "CRITICAL";
        /**
         * ErrorBody
         * @description Every non-2xx response returns this shape as its JSON body.
         *
         *     `code` is a short machine-readable slug (e.g. "not_found", "forbidden",
         *     "validation_error") for client branching; `message` is one sentence a human
         *     reads; `detail` carries whatever extra structure the specific failure needs
         *     (field errors, the resource id that was missing, etc.) and may be null.
         */
        ErrorBody: {
            /** Code */
            code: string;
            /** Detail */
            detail?: unknown | null;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Schema Version */
            schema_version: string;
            /** Status */
            status: string;
        };
        /**
         * OpinionVerdict
         * @description A single governance agent's stance on a recommendation, before opinions are
         *     combined into one Recommendation.
         * @enum {string}
         */
        OpinionVerdict: "CONCUR" | "OBJECT" | "ABSTAIN";
        /** Page[AgentOut] */
        Page_AgentOut_: {
            /** Items */
            items: components["schemas"]["AgentOut"][];
            /**
             * Page
             * @description 1-indexed page number
             */
            page: number;
            /**
             * Page Size
             * @description Items per page, as requested
             */
            page_size: number;
            /**
             * Total
             * @description Total matching records, independent of page size
             */
            total: number;
        };
        /** Page[AuditLogEntryOut] */
        Page_AuditLogEntryOut_: {
            /** Items */
            items: components["schemas"]["AuditLogEntryOut"][];
            /**
             * Page
             * @description 1-indexed page number
             */
            page: number;
            /**
             * Page Size
             * @description Items per page, as requested
             */
            page_size: number;
            /**
             * Total
             * @description Total matching records, independent of page size
             */
            total: number;
        };
        /** Page[AuditSampleOut] */
        Page_AuditSampleOut_: {
            /** Items */
            items: components["schemas"]["AuditSampleOut"][];
            /**
             * Page
             * @description 1-indexed page number
             */
            page: number;
            /**
             * Page Size
             * @description Items per page, as requested
             */
            page_size: number;
            /**
             * Total
             * @description Total matching records, independent of page size
             */
            total: number;
        };
        /** Page[DecisionRecordOut] */
        Page_DecisionRecordOut_: {
            /** Items */
            items: components["schemas"]["DecisionRecordOut"][];
            /**
             * Page
             * @description 1-indexed page number
             */
            page: number;
            /**
             * Page Size
             * @description Items per page, as requested
             */
            page_size: number;
            /**
             * Total
             * @description Total matching records, independent of page size
             */
            total: number;
        };
        /** Page[PolicyVersionOut] */
        Page_PolicyVersionOut_: {
            /** Items */
            items: components["schemas"]["PolicyVersionOut"][];
            /**
             * Page
             * @description 1-indexed page number
             */
            page: number;
            /**
             * Page Size
             * @description Items per page, as requested
             */
            page_size: number;
            /**
             * Total
             * @description Total matching records, independent of page size
             */
            total: number;
        };
        /** Page[RecommendationOut] */
        Page_RecommendationOut_: {
            /** Items */
            items: components["schemas"]["RecommendationOut"][];
            /**
             * Page
             * @description 1-indexed page number
             */
            page: number;
            /**
             * Page Size
             * @description Items per page, as requested
             */
            page_size: number;
            /**
             * Total
             * @description Total matching records, independent of page size
             */
            total: number;
        };
        /** Page[TrustEvaluationOut] */
        Page_TrustEvaluationOut_: {
            /** Items */
            items: components["schemas"]["TrustEvaluationOut"][];
            /**
             * Page
             * @description 1-indexed page number
             */
            page: number;
            /**
             * Page Size
             * @description Items per page, as requested
             */
            page_size: number;
            /**
             * Total
             * @description Total matching records, independent of page size
             */
            total: number;
        };
        /**
         * PolicyVersionOut
         * @description One row of an agent's append-only limit history.
         *
         *     docs/lanes/vp.md: "`policy_versions` is append-only and every decision
         *     references one" — this is what `GET /agents/{agent_id}/policy-versions`
         *     returns, oldest-relevant invariant first: `previous_version_id` chains
         *     each row to the one it replaced, `None` only on an agent's very first
         *     version.
         */
        PolicyVersionOut: {
            /** Agent Id */
            agent_id: string;
            /** Created By */
            created_by: string;
            /**
             * Effective From
             * Format: date-time
             */
            effective_from: string;
            /** Id */
            id: string;
            /** Limit */
            limit: number;
            /** Previous Version Id */
            previous_version_id: string | null;
            /** Reason */
            reason: string;
            /** Rung */
            rung: number;
        };
        /**
         * ProportionResultOut
         * @description Mirrors `shared.contracts.ProportionResult` field-for-field.
         */
        ProportionResultOut: {
            /** Point */
            point: number | null;
            /** Successes */
            successes: number;
            /** Trials */
            trials: number;
            /** Wilson Lower */
            wilson_lower: number;
            /** Wilson Upper */
            wilson_upper: number;
        };
        /**
         * RecommendationDecision
         * @description Request body for both `POST .../approve` and `POST .../reject`.
         *
         *     `reason` is mandatory on both — approving *and* rejecting are mutations,
         *     and the cross-cutting rule doesn't carve out an exception for the
         *     "yes" path. Only ADMIN may call either endpoint (see `app/deps.py`,
         *     `Role.ADMIN` docstring: "Reviewer explicitly cannot approve").
         */
        RecommendationDecision: {
            /**
             * Reason
             * @description Why this decision was made
             */
            reason: string;
        };
        /**
         * RecommendationOut
         * @description Mirrors `shared.contracts.Recommendation` field-for-field.
         */
        RecommendationOut: {
            /** Agent Id */
            agent_id: string;
            /** Clamped */
            clamped: boolean;
            /** Clamped From */
            clamped_from: number | null;
            /** Confidence */
            confidence: number;
            direction: components["schemas"]["Direction"];
            /** Generated At */
            generated_at: string | null;
            /** Governance Mode */
            governance_mode: string;
            /** Has Dissent */
            has_dissent: boolean;
            /** Opinions */
            opinions: components["schemas"]["AgentOpinionOut"][];
            /** Proposed Limit */
            proposed_limit: number;
            /** Proposed Rung */
            proposed_rung: number;
            /** Rationale */
            rationale: string;
            /** Recommendation Id */
            recommendation_id: string;
            /** Schema Version */
            schema_version: string;
            status: components["schemas"]["RecommendationStatus"];
            /** Trust Evaluation Ref */
            trust_evaluation_ref: string | null;
        };
        /**
         * RecommendationStatus
         * @description Lifecycle of a governance recommendation, from proposed to resolved.
         * @enum {string}
         */
        RecommendationStatus: "PENDING" | "APPROVED" | "REJECTED" | "SUPERSEDED";
        /**
         * ReviewVerdict
         * @description A human reviewer's verdict on a sampled decision, from comparing the agent's
         *     action against what the reviewer determines was correct.
         * @enum {string}
         */
        ReviewVerdict: "AGREED" | "DISAGREED" | "INCONCLUSIVE";
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "pending" | "running" | "completed" | "failed";
        /**
         * ScoreComponentOut
         * @description Mirrors `shared.contracts.ScoreComponent` field-for-field.
         */
        ScoreComponentOut: {
            /** Available */
            available: boolean;
            /** Effective Weight */
            effective_weight: number;
            /** Name */
            name: string;
            /** Nominal Weight */
            nominal_weight: number;
            /** Value */
            value: number | null;
        };
        /**
         * SimulationPhase
         * @description Mirrors `simulator.simulator.models.SimulationPhase` by value, not by
         *     import — `simulator/` is a lane the backend must not depend on
         *     (docs/lanes/vp.md: "Do not write code outside backend/"; the simulator
         *     submits to this API, this API does not reach into the simulator).
         * @enum {string}
         */
        SimulationPhase: "good" | "degraded" | "recovery";
        /**
         * SimulationRunCreate
         * @description Request body for `POST /api/v1/simulation/runs`.
         *
         *     Only ADMIN may start a run (`app/deps.py`) — this is an operational
         *     action, not a governance authorization, but it still changes state
         *     (kicks off a batch of decisions), so `reason` is still required.
         */
        SimulationRunCreate: {
            /** Agent Id */
            agent_id: string;
            /** Invoice Count */
            invoice_count: number;
            phase: components["schemas"]["SimulationPhase"];
            /**
             * Reason
             * @description Why this run is being started
             */
            reason: string;
            /**
             * Seed
             * @default 42
             */
            seed: number;
        };
        /**
         * SimulationRunOut
         * @description The status/result of one simulation run.
         */
        SimulationRunOut: {
            /** Accuracy */
            accuracy: number | null;
            /** Agent Id */
            agent_id: string;
            /** Completed At */
            completed_at: string | null;
            /** Decisions Submitted */
            decisions_submitted: number;
            /** Invoice Count */
            invoice_count: number;
            phase: components["schemas"]["SimulationPhase"];
            /** Run Id */
            run_id: string;
            /** Seed */
            seed: number;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["RunStatus"];
            /** Wilson Lower Bound */
            wilson_lower_bound: number | null;
        };
        /**
         * TrustEvaluationOut
         * @description Mirrors `shared.contracts.TrustEvaluation` field-for-field, plus `id`
         *     (see module docstring — this is the one backend-minted addition).
         */
        TrustEvaluationOut: {
            accuracy: components["schemas"]["ProportionResultOut"] | null;
            /** Acted Decisions */
            acted_decisions: number;
            /** Agent Id */
            agent_id: string;
            /** Components */
            components: components["schemas"]["ScoreComponentOut"][];
            /** Config Fingerprint */
            config_fingerprint: string;
            /** Critical Error Rate */
            critical_error_rate: number;
            /** Critical Errors */
            critical_errors: number;
            /** Critical Errors In Recent Window */
            critical_errors_in_recent_window: number;
            /** Current Limit */
            current_limit: number;
            /** Current Rung */
            current_rung: number;
            /** Decisions Since Last Change */
            decisions_since_last_change: number;
            direction: components["schemas"]["Direction"];
            drift: components["schemas"]["DriftResultOut"];
            /** Eligible For Increase */
            eligible_for_increase: boolean;
            /** Escalated Decisions */
            escalated_decisions: number;
            /** Evaluated At */
            evaluated_at: string | null;
            human_agreement: components["schemas"]["ProportionResultOut"] | null;
            /** Id */
            id: string;
            /** Noncritical Errors */
            noncritical_errors: number;
            /** Reason Codes */
            reason_codes: string[];
            /** Recommended Limit */
            recommended_limit: number;
            /** Recommended Rung */
            recommended_rung: number;
            /** Ruled Escalations */
            ruled_escalations: number;
            /** Schema Version */
            schema_version: string;
            state: components["schemas"]["AgentState"];
            /** Total Decisions */
            total_decisions: number;
            /** Trust Score */
            trust_score: number;
            utilization: components["schemas"]["ProportionResultOut"] | null;
            /** Weights Renormalised */
            weights_renormalised: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_agents_api_v1_agents_get: {
        parameters: {
            query?: {
                /** @description 1-indexed page number */
                page?: number;
                /** @description Items per page */
                page_size?: number;
            };
            header?: {
                "X-User-Role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AgentOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_api_v1_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
            };
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"];
                };
            };
            /** @description No resource with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_policy_versions_api_v1_agents__agent_id__policy_versions_get: {
        parameters: {
            query?: {
                /** @description 1-indexed page number */
                page?: number;
                /** @description Items per page */
                page_size?: number;
            };
            header?: {
                "X-User-Role"?: string | null;
            };
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PolicyVersionOut_"];
                };
            };
            /** @description No resource with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_trust_api_v1_agents__agent_id__trust_get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
            };
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustEvaluationOut"];
                };
            };
            /** @description No resource with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trust_history_api_v1_agents__agent_id__trust_history_get: {
        parameters: {
            query?: {
                /** @description 1-indexed page number */
                page?: number;
                /** @description Items per page */
                page_size?: number;
            };
            header?: {
                "X-User-Role"?: string | null;
            };
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TrustEvaluationOut_"];
                };
            };
            /** @description No resource with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_log_api_v1_audit_log_get: {
        parameters: {
            query?: {
                /** @description 1-indexed page number */
                page?: number;
                /** @description Items per page */
                page_size?: number;
            };
            header?: {
                "X-User-Role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditLogEntryOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_samples_api_v1_audit_samples_get: {
        parameters: {
            query?: {
                /** @description 1-indexed page number */
                page?: number;
                /** @description Items per page */
                page_size?: number;
            };
            header?: {
                "X-User-Role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditSampleOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_audit_sample_api_v1_audit_samples__sample_id__review_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
            };
            path: {
                sample_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuditSampleReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditSampleOut"];
                };
            };
            /** @description The current role may not perform this action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description No resource with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The resource is not in a state this action applies to. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_decisions_api_v1_decisions_get: {
        parameters: {
            query?: {
                /** @description 1-indexed page number */
                page?: number;
                /** @description Items per page */
                page_size?: number;
            };
            header?: {
                "X-User-Role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DecisionRecordOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_decision_api_v1_decisions_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionRecordOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_decision_api_v1_decisions__decision_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
            };
            path: {
                decision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionRecordOut"];
                };
            };
            /** @description No resource with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    list_recommendations_api_v1_recommendations_get: {
        parameters: {
            query?: {
                /** @description 1-indexed page number */
                page?: number;
                /** @description Items per page */
                page_size?: number;
            };
            header?: {
                "X-User-Role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RecommendationOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recommendation_api_v1_recommendations__rec_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
            };
            path: {
                rec_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationOut"];
                };
            };
            /** @description No resource with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_recommendation_api_v1_recommendations__rec_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
            };
            path: {
                rec_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationOut"];
                };
            };
            /** @description The current role may not perform this action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description No resource with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The resource is not in a state this action applies to. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_recommendation_api_v1_recommendations__rec_id__reject_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
            };
            path: {
                rec_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationOut"];
                };
            };
            /** @description The current role may not perform this action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description No resource with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The resource is not in a state this action applies to. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_simulation_run_api_v1_simulation_runs_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationRunOut"];
                };
            };
            /** @description The current role may not perform this action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_simulation_run_api_v1_simulation_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Role"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationRunOut"];
                };
            };
            /** @description No resource with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
