"""Initial schema: every table in docs/lanes/vp.md's schema.

Revision ID: 0001
Revises: (none — this is the first migration)
Create Date: 2026-08-31

Hand-reviewed after `alembic revision --autogenerate` (generated against an
empty SQLite database, then checked against `app/models/` table-by-table):
the two JSONB columns (`audit_log.payload`, `recommendations.agent_opinions`,
`trust_evaluations.payload`) correctly render as
`postgresql.JSONB().with_variant(sa.JSON(), "sqlite")`
(`app/models/types.py`), every enum column is `native_enum=False` (a
`VARCHAR` + `CHECK`, not a Postgres `ENUM` type — see that module's
docstring for why), and `ck_agents_rung_matches_limit` is generated from
`shared.constants.AUTONOMY_LADDER` rather than hand-typed.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("current_limit", sa.Integer(), nullable=False),
        sa.Column("current_rung", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "probation",
                "active",
                "restricted",
                "suspended",
                name="agentstate",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(current_limit = 500 AND current_rung = 0) OR (current_limit = 1000 AND current_rung = 1) OR (current_limit = 2500 AND current_rung = 2) OR (current_limit = 5000 AND current_rung = 3) OR (current_limit = 10000 AND current_rung = 4)",
            name="ck_agents_rung_matches_limit",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("actor_type", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("prev_hash", sa.String(), nullable=False),
        sa.Column("hash", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hash"),
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("vendor", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ground_truth_action",
            sa.Enum("APPROVE", "REJECT", "ESCALATE", name="action", native_enum=False),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ground_truth_action IN ('APPROVE', 'REJECT')",
            name="ck_invoices_ground_truth_not_escalate",
        ),
        sa.CheckConstraint("amount > 0", name="ck_invoices_amount_positive"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "reviewer", "auditor", name="role", native_enum=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "policy_versions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("limit", sa.Integer(), nullable=False),
        sa.Column("rung", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("previous_version_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_version_id"],
            ["policy_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trust_evaluations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trust_score", sa.Float(), nullable=False),
        sa.Column("recommended_limit", sa.Integer(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("INCREASE", "HOLD", "CLAWBACK", name="direction", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "decisions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("APPROVE", "REJECT", "ESCALATE", name="action", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "recommended_action",
            sa.Enum("APPROVE", "REJECT", "ESCALATE", name="action", native_enum=False),
            nullable=True,
        ),
        sa.Column(
            "human_ruling",
            sa.Enum("APPROVE", "REJECT", "ESCALATE", name="action", native_enum=False),
            nullable=True,
        ),
        sa.Column("policy_version_id", sa.String(), nullable=False),
        sa.Column("within_limit", sa.Boolean(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_version_id"],
            ["policy_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "sequence", name="uq_decisions_agent_sequence"),
    )
    op.create_table(
        "recommendations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("trust_evaluation_id", sa.String(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("INCREASE", "HOLD", "CLAWBACK", name="direction", native_enum=False),
            nullable=False,
        ),
        sa.Column("proposed_limit", sa.Integer(), nullable=False),
        sa.Column("rationale", sa.String(), nullable=False),
        sa.Column(
            "agent_opinions",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "SUPERSEDED",
                name="recommendationstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("clamped", sa.Boolean(), nullable=False),
        sa.Column("clamped_from", sa.Integer(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trust_evaluation_id"],
            ["trust_evaluations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("recommendation_id", sa.String(), nullable=False),
        sa.Column("decided_by", sa.String(), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "SUPERSEDED",
                name="recommendationstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "verdict IN ('APPROVED', 'REJECTED')", name="ck_approvals_verdict_is_a_human_verdict"
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_samples",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("decision_id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("sampled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewer", sa.String(), nullable=True),
        sa.Column(
            "verdict",
            sa.Enum("AGREED", "DISAGREED", "INCONCLUSIVE", name="reviewverdict", native_enum=False),
            nullable=True,
        ),
        sa.Column(
            "reviewer_action",
            sa.Enum("APPROVE", "REJECT", "ESCALATE", name="action", native_enum=False),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audit_samples")
    op.drop_table("approvals")
    op.drop_table("recommendations")
    op.drop_table("decisions")
    op.drop_table("trust_evaluations")
    op.drop_table("policy_versions")
    op.drop_table("users")
    op.drop_table("invoices")
    op.drop_table("audit_log")
    op.drop_table("agents")
    # ### end Alembic commands ###
